services:
  model-serving-embedder:
    hostname: model-serving-embedder
    container_name: model-serving-embedder
    restart: always
    build:
      context: .
      dockerfile: ./embedder/Dockerfile
      args:
        SERVICE_DIR: embedder
      tags:
        - "chatbot/model-serving-embedder:latest"
    image: chatbot/model-serving-embedder:latest
    ports:
      - "8011:8000"
    environment:
      PROMETHEUS_MULTIPROC_DIR: /app/prometheus_multiproc
      EMBEDDER_MODEL_ID: ${EMBEDDER_MODEL_ID}
      EMBEDDER_DEVICE: ${EMBEDDER_DEVICE}
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./embedder/logs:/app/logs
      - ./embedder/prometheus_multiproc:/app/prometheus_multiproc
      - ./.cache:/app/cache
    command: gunicorn -c gunicorn_conf.py app:app
    networks:
      - human-chatbot

  model-serving-llm:
    hostname: model-serving-llm
    container_name: model-serving-llm
    image: vllm/vllm-openai:v0.6.5
    ipc: host
    restart: always
    ports:
      - "8013:8000"
    environment:
      HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
      HF_HUB_ENABLE_HF_TRANSFER: False
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./.cache:/root/.cache/huggingface/hub
    command: [
      "--model", "${LOCAL_LLM_MODEL_ID}",
      "--device", "${LLM_DEVICE}",
      "--max-model-len", "${MAX_CONTEXT_LEN}",
      "--max-seq-len-to-capture", "${MAX_SEQUENCE_LENGTH}",
      "--gpu-memory-utilization", "${GPU_MEMORY_UTILIZATION}",
      "--dtype", "${LOCAL_LLM_DTYPE}",
      "--trust-remote-code",
      "--port", "8000",
      # "--disable-frontend-multiprocessing", # Uncomment this line if you're hosting LLM in WSL, which will cause error "zmq.error.ZMQError: Operation not supported"
      # "--enforce-eager", # Uncomment this line if your GPU memory is not enough
    ]
    networks:
      - human-chatbot
  
networks:
  human-chatbot:
    name: human-chatbot
    external: true