# See: https://neo4j.com/docs/operations-manual/current/docker/introduction/
services:
  neo4j:
    image: neo4j:5.25.1
    container_name: neo4j
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./.data/data:/data
      - ./.data/plugins:/plugins
      - ./.data/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    restart: always
    networks:
      - human-chatbot

networks: 
  human-chatbot:
    name: human-chatbot
    external: true
